### PR TITLE
Add chaadow mapping to Chedli Bourguiba

### PR DESCRIPTION
**Pull request by chaadow**
Hi @jonathanhefner as requested, here is the mapping for my contribution on https://github.com/rails/rails/pull/50044

### CODE REVIEW

**Review by jonathanhefner — APPROVED** [review]

**Review by jonathanhefner — APPROVED** [review]
@chaadow LGTM, but I do not have commit rights for this repo.

I see that your most recent contributions are also credited as [chaadow](https://contributors.rubyonrails.org/contributors/chaadow/commits) rather than [Chedli Bourguiba](https://contributors.rubyonrails.org/contributors/chedli-bourguiba/commits).  As I mentioned in https://github.com/rails/rails/pull/50044#issuecomment-1808817496, if you prefer "Chedli Bourguiba", you might want to set your git username via the [`GIT_AUTHOR_NAME` environment variable](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) or the [`user.name` config](https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git).

**Comment by chaadow** [comment]
Thanks @jonathanhefner!

@fxn Could you please take a look? 🙏🏼

**Comment by fxn** [comment]
Hey @chaadow! Thanks for the ping. Looking good, it will be soon in production.

**Comment by fxn** [comment]
@chaadow there you go! https://contributors.rubyonrails.org/contributors/chedli-bourguiba/commits

Thank you! :)

**Comment by chaadow** [comment]
@fxn let's go! thanks a lot!

**Pull request merged**
