### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by rafaelfranca**
Those sha were being incorrectly mapped to those names, but if you
look their content they don't really references those contributors.

With this commit we update to shas that references those contributors.

For robby, I could not find any sha that contain his name, so I removed
the test.

Example https://github.com/rails/rails/commit/2f40936

### CODE REVIEW

**Comment by fxn** [comment]
This is strange, those mappings have been there for years. What made you edit these particular commits?

The change for Dan seems good. The commit d9c0a37 has a line for him, but is an edited one (red and green), not an addition. On the other hand, 58f2bd0c is legit.

Same for Josh.

I believe the test for Robby Russell should stay, because 2f40936 has a CHANGELOG where he is credited for one entry (the way it was done in the SVN days). Do you seem something wrong in that attribution?

**Comment by fxn** [comment]
Highly suspicious, let me investigate a bit.

**Comment by fxn** [comment]
I've seen the commit for Robby Russel gets assigned just David in 2.6 too, something weird is going on.

**Comment by rafaelfranca** [comment]
Hey @fxn, were you able to see investigate this?

**Comment by fxn** [comment]
Hi @rafaelfranca! I spent some time, but was not able to find the reason. I think we could move on with this patch to unblock, because the reality is those credits are corrected, and the rest of the suite passes as it is.

**Review by fxn — APPROVED** [review]

**Pull request merged**
