### PR TITLE
Update canonical name to merge contributions

### PR DESCRIPTION
**Pull request by alessandrapereyra**
As stated above, just a minor commit to merge contributions.

### CODE REVIEW

**Comment by fxn** [comment]
Hi! I cannot see that handler in https://contributors.rubyonrails.org/, please note that we only map handlers that do have commits associated.

**Comment by alessandrapereyra** [comment]
@fxn I was under the impression it was using the GitHub Handle. Shall I use the Contributor name to bundle it here then?

**Comment by fxn** [comment]
This application works with the information found in Git commits.

For example, the one currently associated to you is

```
% git show fabd2ce
commit fabd2ce24f033e5a20ca447064e4f9af0a2177e6
Merge: c6219b0215 da4252f4a1
Author: Xenda <xendaccount@xendacentral.com>
Date:   Sun May 27 23:42:52 2012 -0700

    Merge pull request #102 from xenda/master
    
    Small fix to update the README using more up to date conventions.
```

Rails Contributors says, "in principle, that is "Xenda", but "Xenda" is mapped to "Alessandra Pereyra", so actually give credit to that name". That is how that commit ends up in your page https://contributors.rubyonrails.org/contributors/alessandra-pereyra/commits.

**Comment by fxn** [comment]
Hey, it's been a while!

I do not see which commits have to be merged, there's still no commit associated to `alessapereyra`. Please, if I am missing something feel free to followup.

**Pull request closed without merging**
