### PR TITLE
fix credit: piecehealth -> Zhang Kang

### PR DESCRIPTION
**Pull request by piecehealth**
[Zhang Kang](https://contributors.rubyonrails.org/contributors/zhang-kang/commits) is my canonical name and [piecehealth](https://contributors.rubyonrails.org/contributors/piecehealth/commits) is my nickname, please help to merge them, thanks.

### CODE REVIEW

**Comment by fxn** [comment]
Sure! Could you please add a test case in https://github.com/rails/rails-contributors/blob/master/test/credits/canonical_names_test.rb? Please, note they are ordered alphabetically by nickname.

**Comment by piecehealth** [comment]
@fxn test added, thanks for the help.

**Comment by fxn** [comment]
Thanks! After merging, should in production in a while.

**Comment by fxn** [comment]
There you go https://contributors.rubyonrails.org/contributors/zhang-kang/commits.

Thanks! ❤️

**Comment by piecehealth** [comment]
Thank you ! ❤️

**Pull request merged**
