### PR TITLE
Make website responsive

### PR DESCRIPTION
**Pull request by MatheusRich**
This uses CSS and a bit of JS to make the website responsive. Some CSS was updated to more modern version. For instance, images were used to add a shadow on the main content. That was replaced by a box-shadow. The navigation element is inside a details/summary element, so it can be toggled on mobile devices to save space. It is closed by default on mobile devices, but open on desktops.

I tried to keep the design as close as possible of the original.

## Before x After

Desktop mode:
<div>
image
image
</div>

Mobile:
<div>
image
image
</div>

## Next steps

From here we could update the styles to match the new Rails website and guides. I'm happy to work on that.

### CODE REVIEW

**Comment by fxn** [comment]
OMG, thanks very much!

> From here we could update the styles to match the new Rails website and guides. I'm happy to work on that.

That'd be awesome.

**Comment by MatheusRich** [comment]
@fxn wow, that was fast! TY. Working on that next! 🚀

**Comment by fxn** [comment]
Deployed!

**Comment by MatheusRich** [comment]
@fxn do you have the original image for the logo? It is using an old gif. We could improve the quality of that.

**Comment by fxn** [comment]
The original file was this one.

logo

**Comment by fxn** [comment]
This design is from 2009 :).

**Comment by MatheusRich** [comment]
😅 Gotcha. I can try recreating it. Do you happen to know the font?

**Comment by fxn** [comment]
Let me /cc @josespinal, he did the design (hey man!!!).

**Comment by fxn** [comment]
Hey, if I follow contributor links, the navigation sidebar is rendered collapsed. Can we fix that?

**Comment by MatheusRich** [comment]
@fxn I just opened #292

**Comment by josespinal** [comment]
> Contributor



> 😅 Gotcha. I can try recreating it. Do you happen to know the font?

The font for this was FF Meta Pro Black. It's a licensed font. A free version that would be an alternative to this is Merriweather Sans: https://fonts.google.com/specimen/Merriweather+Sans?preview.text=RailsContributors

**Comment by josespinal** [comment]
@MatheusRich I'm interested in helping. If I can be of help in anything, let me know!

**Comment by MatheusRich** [comment]
An alternative would be using a design like the [Guides](https://guides.rubyonrails.org/action_text_overview.html). Put the Rails logo and "Contributors" as normal text
image

**Comment by fxn** [comment]
Hey, I am seeing a few issues.

In desktop, I liked the original sidebar better. It is clean, no "header" and not mean to be collapsible. It is a sidebar.

I have also seen that the individual pages render a bit odd in my phone, see screenshot below.

I think we have two options:

1. Iterate these details
2. Go back to the original design and think about this from the start in the new one.

What would you prefer?

Screenshot_20240824-111810_Chrome | width=10

**Comment by MatheusRich** [comment]
@fxn I can iterate on those, for sure. I rather have the website 80% working on mobile for the time being than 0%.

I can definitely hide the navbar toggle on desktop. I'll open PRs for those items. TY

**Pull request merged**
