### PR TITLE
Add mapping for Petra Jaros

### PR DESCRIPTION
**Pull request by nertzy**

### CODE REVIEW

**Comment by fxn** [comment]
You do not seem to be Petra Jaros, could you please provide more context to this patch please?

Also, could you please remove one of the assertions? As you'll see, in this file we only have one per mapping.

**Comment by Peeja** [comment]
Hello! I'm Petra Jaros (and I approve this message). Thanks for the PR, @nertzy!

**Comment by fxn** [comment]
Awesome, thanks for the heads up Petra!

**Comment by fxn** [comment]
[In production](https://contributors.rubyonrails.org/contributors/petra-jaros/commits), welcome Petra!  🎉

**Pull request merged**
