### PR TITLE
Fix CSS for sidebar on the contributors page

### PR DESCRIPTION
**Pull request by yashLadha**
Before:
image

After:
image

### CODE REVIEW

**Comment by yashLadha** [comment]
@tenderlove @rafaelfranca Could you please look into this?

**Comment by fxn** [comment]
Could you please submit a minimal patch?

**Comment by fxn** [comment]
Also, where do you see that misplacement? The site looks normal in Chrome, Firefox, and Safari over here.

**Comment by yashLadha** [comment]
On my machine it looked as in the pr description and also similiar in icognito. Changes are just linting as styling is incosistent in the file. Not any impacting changes @fxn

**Comment by fxn** [comment]
Anyway, I prefer a minimal patch if you are so kind.

**Comment by yashLadha** [comment]
Okay doing that 😅 @fxn

**Comment by yashLadha** [comment]
Probably an issue with one of my installed extension, working fine in icognito @fxn . Closing this.

**Comment by fxn** [comment]
Thanks anyway!

**Pull request closed without merging**
