### PR TITLE
Drew -> Drew Bragg

### PR DESCRIPTION
**Pull request by DRBragg**
I have 2 commit as `Drew Bragg` and one as `Drew`. No idea what happened, I'm sorry...

### CODE REVIEW

**Comment by DRBragg** [comment]
I was curious how it would handle that. I'm happy to update `hard_coded_authors` instead

**Comment by DRBragg** [comment]
Fixed

**Comment by kaspth** [comment]
Sweet!

**Comment by fxn** [comment]
Up https://contributors.rubyonrails.org/contributors/drew-bragg/commits.

The patch was correct, but I try to reserve hard coded associations to a bare minimum of SHA1s for which the metadata just does not contain the author information. You can see each one of those exceptions has an explanation.

As you said, mapping "Drew" would be too generic, but for cases like this we have a middle path in which we disambiguate the "too common name" with the email in the Git metadata ([here](https://github.com/rails/rails-contributors/blob/8fc8add5cfcae380a3150e56efbb3e31c63b6c2f/app/models/names_manager/canonical_names.rb#L23)). That way, also, If Drew had that Git config in some machine and merges a commit whose metadata looks the same, it will be credited to him again automatically.

**Comment by DRBragg** [comment]
@fxn Thanks for the explanation! I'm sorry I didn't do it correctly in this PR would you like me to open another one with the correct code?

**Comment by fxn** [comment]
@DRBragg No prob! It was an edge case and you need to be familiar with the trade-offs in the heuristics for this particular one :). I updated the code myself (https://github.com/rails/rails-contributors/commit/8fc8add5cfcae380a3150e56efbb3e31c63b6c2f).

Thanks for the patch, and thanks for your contributions to Rails ❤️.

**Comment by DRBragg** [comment]
Awesome! Thanks @fxn

**Pull request merged**
