### PR TITLE
Add a canonical mapping to akhilgkrishnan

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
Added a mapping for my name
akhilgkrishnan  -> Akhil G Krishnan

### CODE REVIEW

**Comment by akhilgkrishnan** [comment]
@fxn Can you review this PR?

**Comment by fxn** [comment]
Hi! The test suite for canonical names only covers the mappings, "without the maaping, this would not have been the credited author, with the mapping it is".

Could you please delete the first of the two tests?

**Comment by akhilgkrishnan** [comment]
> Hi! The test suite for canonical names only covers the mappings, "without the mapping, this would not have been the credited author, with the mapping it is".
> 
> Could you please delete the first of the two tests?

@fxn Updated the test.

**Comment by fxn** [comment]
Thanks! I need to do some work to be able to deploy (new laptop). I'll ping you back when it is in production.

**Comment by akhilgkrishnan** [comment]
> Thanks! I need to do some work to be able to deploy (new laptop). I'll ping you back when it is in production.

Thanks, @fxn :)

**Comment by akhilgkrishnan** [comment]
@fxn Did you get a chance to deploy the changes?

**Comment by fxn** [comment]
No!

**Comment by fxn** [comment]
Up! https://contributors.rubyonrails.org/contributors/akhil-g-krishnan/commits

**Pull request merged**
