### PR TITLE
use zzak canonically

### PR DESCRIPTION
**Pull request by zzak**

### CODE REVIEW

**Comment by fxn** [comment]
Hi man! Could you please remove the first test? The suite for canonical names checks that aliases are mapped to the canonical name (the second test). That canonical names are assigned when they appear is the regular logic tested generally.

**Comment by fxn** [comment]
Also, could you please use single quotes?

**Comment by zzak** [comment]
Hello bro! I think I made the changes you requested, thanks for taking a look!

**Comment by fxn** [comment]
[In production](https://contributors.rubyonrails.org/contributors/zzak/commits), thanks @zzak!

**Comment by zzak** [comment]
Thank you!!

**Pull request merged**
