### PR TITLE
Development with Docker

### PR DESCRIPTION
**Pull request by yhirano55**
Using docker, it becomes easily to develop locally (In especially, it become easily to setup middleware)

## Commands

```
# after checkout this branch...
$ docker-compose up -d --build # boot containers
$ docker-compose exec app bin/setup # setup
$ docker-compose exec app rails runner "Repo.sync"
$ docker-compose exec app rails test # test suite
$ docker-compose down # resume containers
```

## Screenshot

image

### CODE REVIEW

**Comment by fxn** [comment]
Hey, this week is for me the final sprint for a conference. Won't be very active in the next days over here, but will be back as soon as I can.

By the way, for development I tend to prefer to mount the current directory as a volume. You rebuild the image when gems change, but otherwise you can get a shell and tinker while editing in the host.

What do you think?

**Comment by fxn** [comment]
Ah, sorry, `docker-compose.yml` has the volume set, does it make sense to have the `COPY` in the Dockerfile?

**Comment by yhirano55** [comment]
In the future, I thought it might use Dockerfile on production env. So I added `COPY` to the app image for keeping its portability. But this PR's scope is for development env, it's better remove `COPY` line, I felt.

**Comment by yhirano55** [comment]
I've removed `COPY` line. And I confirmed that the app can correctly boot on docker.

**Comment by fxn** [comment]
Heads up! I'll work on this one soon.

**Comment by fxn** [comment]
I have merged this (but did a rebase and the merge was not automatically marked here).

Have been working all weekend on this setup. Starting from your work, I have done a complete pass. There are too many details to list, but it is all in one single commit if you'd like to have a look (c12b4485605875c920ffd220d81dad63579b5683).

Thanks for working on this @yhirano55!

**Comment by fxn** [comment]
Ah, by the way, I am sure this is not final, we'll polish as we use it and things arise. Need to check deployment too.

**Pull request closed without merging**
