### PR TITLE
Upgrade Rails 5.2

### PR DESCRIPTION
**Pull request by yhirano55**
## Summary

* Executed `bundle update rails`
* Executed `rails app:update`, and discarded unnecessary changes.
* Applied [5.2 framework defaults](https://github.com/rails/rails/blob/v5.2.0/railties/lib/rails/application/configuration.rb#L90-L122), and remove protect_from_forgery in ApplicationController.
* Move `byebug` gem group from development only to development, test group.
* Fixtures behavior is changed, fixed CommitsControllerTest.

### CODE REVIEW

**Comment by yhirano55** [comment]
### Screenshot

image

```
% bin/rails db:reset
% bin/rails r Repo.sync
% bin/rails server
```

### Test result

```
% bin/rails test
Run options: --seed 11857

# Running:

......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Finished in 13.049772s, 104.6762 runs/s, 136.4009 assertions/s.
1366 runs, 1780 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by yhirano55** [comment]
Please enable CircleCI whenever you like or can :pray:

**Comment by yhirano55** [comment]
All tests have passed in my forked repo's ci.
https://circleci.com/gh/yhirano55/rails-contributors/10

**Comment by fxn** [comment]
CircleCI seems to be enabled. Do we need to do anything else to run it with PRs and report status? Or is it automatic? Didn't find information on this.

screen shot 2018-04-19 at 21 47 20

**Pull request merged**
