### PR TITLE
Fixed commit issue for alkesh26

### PR DESCRIPTION
**Pull request by alkesh26**
Fixes: #173

### CODE REVIEW

**Comment by fxn** [comment]
Hey!, We'd need a test for `alkesh26` too, and both of them would be placed alphabetically in the test file. Like the rest.

**Comment by alkesh26** [comment]
Hey @fxn pushed the changes.

**Comment by alkesh26** [comment]
Hey @fxn can we merge this PR if no other changes are required?

**Comment by fxn** [comment]
It's live https://contributors.rubyonrails.org/contributors/alkesh-ghorpade/commits, thanks!

**Comment by alkesh26** [comment]
Hey @fxn thanks a lot 👍 👍

**Pull request merged**
