### PR TITLE
Fix author of 1d133e8

### PR DESCRIPTION
**Pull request by javan**
References
- https://github.com/rails/rails/commit/1d133e8a4725439e4a61d53ce913eba9dcab42d3
- https://github.com/rails/rails/pull/38124#issuecomment-571844508

<details>

Screen Shot 2020-01-08 at 3 39 55 PM
---
Screen Shot 2020-01-08 at 3 40 09 PM
---
https://contributors.rubyonrails.org/contributors/direct_upload_xls_in_chrome/commits

</details>

### CODE REVIEW

**Comment by javan** [comment]
Does someone have to press <kbd>Deploy</kbd>?

**Comment by rafaelfranca** [comment]
done

**Comment by javan** [comment]
Hmm, I guess my change didn't do the trick: https://contributors.rubyonrails.org/contributors/direct_upload_xls_in_chrome/commits 🤔

**Comment by fxn** [comment]
This one in principle would go as a [false positive](https://github.com/rails/rails-contributors/blob/master/app/models/names_manager/false_positives.rb), hard-coding is the last resort. I'll revise and redeploy.

**Comment by fxn** [comment]
I have forced a rebuild of the credits table, and now the credit is correct.

I have investigated why didn't the database get updated.

When the Rails repo is updated, the application imports new commits into the database, and computes the credit only for those ones. However, if the heuristics in the name manager changed, the entire credits table is recomputed. This is figured out comparing the last repo updates with the mtimes of the files under `app/models/names_manager`.

This works well routinely, but for some reason it did not when Rafael deployed, here's the last updates:

```
         started_at         |          ended_at          | rebuild_all
----------------------------+----------------------------+-------------
 2020-01-11 17:33:36.719541 | 2020-01-11 17:34:11.758509 | t
 2020-01-10 23:54:06.935055 | 2020-01-10 23:54:12.570309 | f
 2020-01-10 23:51:07.836452 | 2020-01-10 23:51:14.250092 | f
 2020-01-10 21:35:06.583443 | 2020-01-10 21:35:13.077191 | f
 2020-01-10 20:39:07.008038 | 2020-01-10 20:39:12.463535 | f
 2020-01-10 19:52:07.630503 | 2020-01-10 19:52:14.30941  | f
 2020-01-10 19:50:14.62112  | 2020-01-10 19:50:21.059344 | f
 2020-01-10 19:18:07.21799  | 2020-01-10 19:18:11.85158  | f
 2020-01-10 19:11:07.575085 | 2020-01-10 19:11:13.462929 | f
 2020-01-10 18:51:06.721418 | 2020-01-10 18:51:12.419932 | f
```

See? No `rebuild_all` is `t`.

The release directory is (edited) `2020-01-10 21:33:54`, and the mtime of the files is way earlier:

```
rails@cantor:~/rails-contributors/current$ ls -l app/models/names_manager
total 76
-rw-r--r-- 1 rails rails 63844 Jan 10 18:58 canonical_names.rb
-rw-r--r-- 1 rails rails  3204 Jan 10 18:58 false_positives.rb
-rw-r--r-- 1 rails rails  5404 Jan 10 18:58 hard_coded_authors.rb
```

So I believe the reason is that there was an update to the Rails repo between the modifications and the actual deploy.

I guess a deploy should force a full credits rebuild to avoid this situation.

**Comment by javan** [comment]
Thank you!

**Pull request merged**
