### PR TITLE
Fix Ruby version for CircleCI

### PR DESCRIPTION
**Pull request by albertoalmagro**
### Summary
Currently CI build for master is failing because CircleCI is using Ruby 2.5.3 while our Gemfile indicates version 2.5.1. See build error [here](https://circleci.com/gh/rails/rails-contributors/32?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

The origin of the issue is that CircleCI choses its Ruby version based on the version set in the `.ruby-version`. See docs [here](https://circleci.com/docs/2.0/testing-ios/#using-custom-ruby-versions).

As we don't have a `.ruby-version` file at the moment, CircleCI doesn't know which version should be used.

This patch:
* Adds `.ruby-version` file so that CircleCI knows which Ruby version should be used.

### CODE REVIEW

**Comment by fxn** [comment]
Thanks for fixing this Alberto!

The production server is using 2.5.1 right now, better to keep it at that version by now.

**Comment by albertoalmagro** [comment]
Thanks Xavier! Let me then only add the `.ruby-version` file pointing to 2.5.1

**Comment by fxn** [comment]
❤️

**Comment by albertoalmagro** [comment]
@fxn CI build is still failing.

In the docs I find contradictory information about how to specify the Ruby version. While in some places it says you should configure a `.ruby-version` file (and it seems to have worked for some people) in others it says that it depends on your docker image, but if docker image was the case, it doesn't make sense to me that if we specify Ruby 2.4 [here](https://github.com/rails/rails-contributors/blob/fix-ci/.circleci/config.yml#L8) it ends picking 2.5.3.

The solution with the `.ruby-version` made more sense to me, know it is confusing. Will check later.

**Pull request merged**
