### PR TITLE
Upgrade rugged 0.21.0 to 0.27.0

### PR DESCRIPTION
**Pull request by yhirano55**
## Summary

* It's no problem to upgrade rugged from 0.21.0 to 0.27.0.
* [CHANGELOG](https://github.com/libgit2/rugged/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by fxn** [comment]
Could you please start from a blank database and see if `Repo.sync` is able to deal with the entire history?

**Comment by yhirano55** [comment]
@fxn Thanks for the comment. I did check it's no problem on development:

## Executed commands

```
$ bin/rails db:reset
$ bin/rails r Repo.sync
$ bin/rails s
```

## Screenshot

image

---

BTW seems that updating history is not working correctly on prod.

## Production

image

## Development

image

**Comment by fxn** [comment]
Awesome, thanks a lot for working on this project! ❤️

**Comment by yhirano55** [comment]
I respect core team and all rails contributors, so I'll continuously send patches to this repo. Thanks.

**Pull request merged**
