### PR TITLE
Map tleneveu to Thibaut Leneveu

### PR DESCRIPTION
**Pull request by tleneveu**

### CODE REVIEW

**Comment by tleneveu** [comment]
Thanks @rafaelfranca

**Comment by tleneveu** [comment]
@rafaelfranca, @fxn Could you deploy the changes?

Thank you very much!

**Comment by fxn** [comment]
I am on a cruise, won’t have a computer till Sunday.
-- 
Sent from Gmail Mobile

**Comment by tleneveu** [comment]
@fnx No problem 😃

**Comment by rafaelfranca** [comment]
haha. I'll do it. Enjoy @fxn 🚢

**Comment by rafaelfranca** [comment]
Deployed. The new name should show when the next build happen.

**Comment by tleneveu** [comment]
@rafaelfranca @fxn It's confirmed!

Thank you! ❤️

**Pull request merged**
