### PR TITLE
Add Jean-François Labbé mapping

### PR DESCRIPTION
**Pull request by jean-francois-labbe**
This commit is not linked to me https://github.com/rails/rails/commit/90d5a5c2aba556053cbd3f5eea31fc855ba3bc9f Name is `Jean-François Labbé`

This one was linked: https://github.com/rails/rails/commit/34916855ca949262ceb80ca476d452b799c13c5d name is `jean-francois labbe`

### CODE REVIEW

**Comment by fxn** [comment]
Could you please remove the second "Jean-François Labbé"? the first argument is the canonical name, and the rest are existing aliases (different from the canonical name).

**Comment by jean-francois-labbe** [comment]
Thanks for the explanation.
I fixed the mapping.

**Comment by fxn** [comment]
Thanks! I'll deploy soon.

**Comment by fxn** [comment]
I've deployed but your name for some reason does not appear.

This is very strange, this application has been working routinely for years without any known flaw. I need to investigate. Don't worry, we'll figure it out and restore it.

**Comment by jean-francois-labbe** [comment]
Thanks for the follow up.
Indeed it seems that some commits are missing.
Here are the PR on github https://github.com/rails/rails/pulls?q=is%3Apr+author%3Ajean-francois-labbe+is%3Aclosed

**Pull request merged**
